import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { roboto_font } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className} ${roboto_font}`}>
        <div className="w-screen h-auto bg-[#F8F7F1]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
